"""Memory management agent package."""

from .agents import (
    BaseAgent,
    EmbeddingRetrievalAgent,
    KeywordRetrievalAgent,
    NoMemoryAgent,
    PreferenceOnlyAgent,
    RuleBasedMemoryAgent,
    StoreEverythingAgent,
)
from .environment import MemoryManagementEnv
from .episode import SyntheticEpisodeGenerator
from .grader import Grader, RewardComposer, normalize_task_score
from .evaluation import BenchmarkReport, EvaluationSummary, evaluate_split, hidden_eval_seeds, run_episode
from .analysis import AnalysisReport, FailureCase, MemoryTurnSnapshot, analyze_rollouts, memory_evolution_text, summarize_memory_evolution
from .memory_store import MemoryStore
from .training import (
    PromptBundle,
    RolloutEpisode,
    RolloutStep,
    TrainingConfig,
    TrainingRunReport,
    build_policy_prompt,
    collect_rollouts,
    export_rollouts_jsonl,
    parse_action_block,
    run_training_data_collection,
    run_training_experiment,
    summarize_rollouts,
)
from .review import render_failure_cases, render_full_review, render_memory_evolution, render_training_run_summary
from .tasks import ALL_TASKS, TASK_BY_ID, TASK_EASY, TASK_HARD, TASK_MEDIUM, TaskDefinition, TaskEpisodeGenerator, generator_for_task
from .schemas import (
    Action,
    ActionType,
    ConversationTurn,
    Episode,
    EpisodeResult,
    GraderMetrics,
    MemoryItem,
    MemoryType,
    Observation,
    StepResult,
)

__all__ = [
    "Action",
    "ActionType",
    "AnalysisReport",
    "BaseAgent",
    "BenchmarkReport",
    "EmbeddingRetrievalAgent",
    "ConversationTurn",
    "Episode",
    "EpisodeResult",
    "Grader",
    "GraderMetrics",
    "EvaluationSummary",
    "FailureCase",
    "KeywordRetrievalAgent",
    "PromptBundle",
    "MemoryItem",
    "MemoryTurnSnapshot",
    "MemoryManagementEnv",
    "MemoryStore",
    "MemoryType",
    "NoMemoryAgent",
    "Observation",
    "PreferenceOnlyAgent",
    "RewardComposer",
    "RuleBasedMemoryAgent",
    "RolloutEpisode",
    "RolloutStep",
    "TrainingConfig",
    "TrainingRunReport",
    "StepResult",
    "StoreEverythingAgent",
    "SyntheticEpisodeGenerator",
    "build_policy_prompt",
    "analyze_rollouts",
    "collect_rollouts",
    "evaluate_split",
    "export_rollouts_jsonl",
    "hidden_eval_seeds",
    "parse_action_block",
    "run_training_data_collection",
    "run_training_experiment",
    "run_episode",
    "memory_evolution_text",
    "render_failure_cases",
    "render_full_review",
    "render_memory_evolution",
    "render_training_run_summary",
    "summarize_rollouts",
    "summarize_memory_evolution",
    "normalize_task_score",
    "ALL_TASKS",
    "TASK_BY_ID",
    "TASK_EASY",
    "TASK_MEDIUM",
    "TASK_HARD",
    "TaskDefinition",
    "TaskEpisodeGenerator",
    "generator_for_task",
]
